model:
  num_encoding_layers: 4
  dropout: 0.15

train:
  epochs: 10
  train_batch_size: 64
  validation_batch_size: 64
  base_lr: 0.00002
  weight_decay: 0.00005
  checkpoint_dir: 'checkpoints'
  initial_checkpoint: 'checkpoints/best.pt'

test:
  run_tests: true
  batch_size: 32