model:
  num_encoding_layers: 4
  dropout: 0.15

train:
  epochs: 50
  train_batch_size: 32
  validation_batch_size: 32
  base_lr: 0.0003
  weight_decay: 0.00005
  checkpoint_dir: 'checkpoints'
  initial_checkpoint: 'checkpoints/best.pt'

test:
  run_tests: true
  batch_size: 32